[package]
name = "typeaot"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
oxc = { version = "0.46.0", features = ["full", "serialize"] }
pico-args = "0.5.0"
serde = "1.0.216"
serde_json = "1.0.134"
